// <auto-generated />
namespace Meeting.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ajustefk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajustefk));
        
        string IMigrationMetadata.Id
        {
            get { return "202011190434525_ajuste-fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
